name: CI/CD Pipeline

on:
  push:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Verificar app
        run: |
          python -m app.main & 
          sleep 5
          curl http://localhost:5000 || exit 1

      - name: Build Docker
        run: docker build -t test-image .


  cd:
    runs-on: ubuntu-latest
    needs: ci   #SOLO corre si CI pasa

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build imagen
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:latest .

      - name: Push imagen
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
        
      - name: Deploy en VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
            docker stop flask_app || true
            docker rm flask_app || true
            docker run -d -p 5000:5000 --name flask_app ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

